name: Kafka Docker-Compose CI/CD

on:
  # push:
  #   branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Validate Docker Compose
      run: docker compose -f docker-compose.yml config

    - name: Lint Shell Scripts
      uses: azohra/shell-linter@latest
      with:
        path: "*.sh"

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Start Kafka services
      run: docker compose up -d

    - name: Wait for Kafka to be ready
      run: |
        timeout 300s bash -c '
        until docker compose exec -T kafka /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list; do
          echo "Waiting for Kafka to be ready..."
          sleep 5
        done'

    - name: Run Kafka tests
      run: |
        docker compose exec -T kafka /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --topic test-topic --partitions 1 --replication-factor 1
        echo "Test message" | docker compose exec -T kafka /opt/kafka/bin/kafka-console-producer.sh --bootstrap-server kafka:9092 --topic test-topic
        docker compose exec -T kafka /opt/kafka/bin/kafka-console-consumer.sh --bootstrap-server kafka:9092 --topic test-topic --from-beginning --max-messages 1 --timeout-ms 10000

    - name: Stop Kafka services
      run: docker compose down

    - name: Debug Kafka setup
      if: failure()
      run: |
        docker compose ps
        docker compose exec kafka ls /opt/kafka/bin
        docker compose exec kafka cat /opt/kafka/config/kraft/server.properties